stages:
  - build
  - test
  - publish

build-job:
  stage: build
  image: node:22
  script:
    - npm ci
    - npm run build

unit-test-job:
  stage: test
  image: node:22
  script:
    - npm run test

#lint-test-job:
#stage: test
#image: node:22
#script:
# - npm run lint

publish-job:
  stage: publish
  image: node:22
  environment: production
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - npm run publish
  only:
    - main
  variables:
    NPM_TOKEN: $NPM_TOKEN
